Subscription refactor
coasys/ad4m-core-deprecated pull request #45
Opened 2022-07-20 09:49 UTC by kaichaosun

Changes,

- when build an ad4mClient, it should pass a flag to subscribe all the endpoints or not.
- perspective link added/removed subscription is moved from PerspectiveProxy to PerspectiveClient, this change assume same callbacks for different perspectives, probably not the best, but making a map (perspectiveUuid -> callbacks) in PerspectiveClient seems overkill for now.

Fix https://github.com/perspect3vism/ad4m/issues/43

2022-07-21 06:26 UTC, fayeed commented on src/perspectives/PerspectiveClient.ts
> +                this.#perspectiveLinkAddedCallbacks.forEach(cb => {
Won't this call all the callbacks that have been added to the client not just the callback for the perspective, maybe maintaining a Map to handle this would be better?

2022-07-21 06:26 UTC, fayeed commented on src/perspectives/PerspectiveClient.ts
> +                this.#perspectiveLinkRemovedCallbacks.forEach(cb => {
Same here.

2022-07-21 09:15 UTC, kaichaosun commented on src/perspectives/PerspectiveClient.ts
> +                this.#perspectiveLinkAddedCallbacks.forEach(cb => {
Maintaining a map sounds good, but I don't see the real use case yet. Do you have some in you mind? @fayeed

2022-07-21 09:35 UTC, fayeed commented on src/perspectives/PerspectiveClient.ts
> +                this.#perspectiveLinkAddedCallbacks.forEach(cb => {
What I was saying when you register a callback and what a link gets added this would trigger all the registered callbacks not just the callbacks registered for the perspective.

2022-07-21 12:32 UTC, jdeepee requested changes
Small question and also agree with Fayeed that its better if not all the callbacks are hit on a perspective mutation but only the subscriptions for that perspective. I think otherwise we may have to do some complex / filtering thing on the front end to deal with this.

2022-07-21 12:32 UTC, jdeepee commented on src/Ad4mClient.test.ts
>              await perspective.add({source: 'root', target: 'neighbourhood://Qm123456'})
Should this be perspective.remove() not perspective.add()?

2022-07-21 14:11 UTC, kaichaosun commented
> Small question and also agree with Fayeed that its better if not all the callbacks are hit on a perspective mutation but only the subscriptions for that perspective. I think otherwise we may have to do some complex / filtering thing on the front end to deal with this.

I was thinking that there may be requirements for ad4m-client, to both provide **same callbacks** for different perspectives, and **different callbacks** for different perspectives, so the better solution for these requirements is let each callback decide how to behave on different perspectives based on some meta info, tags, signature or links of the perspective.

It would be good if you guys can provide more context on how this function is used in Flux. @fayeed @jdeepee

2022-07-22 09:00 UTC, kaichaosun commented
Finish mapping from perspective id to linkAdded/linkRemoved callbacks. 
also clear the test.

2022-07-25 16:24 UTC, lucksus requested changes
I would like to avoid changing the interface that much just for optional subscriptions. In particular:
1. Don't remove the callback-adding functions on PerspectiveProxy. I regard that as the recommended way of adding callbacks. I'm doing that a lot in Perspect3ve.
2. Having the default (i.e. if no flag is provided to the constructor) install the subscriptions.

In other words: I would like this PR to pass tests without any changes on the tests. Maybe an additional tests, that only tests the new feature of not installing subscriptions if so requested.

2022-07-26 01:36 UTC, kaichaosun commented
@lucksus I'm not concerned with broken changes actually,
- we are still in early version at 0.1.*, it's better break it now not later if the change makes sense. The broken changes makes the downstream apps like perspect3ve and flux a burden, but it will make future apps and future versions of perspect3ve easier.
- The reason I didn't put the default flag in constructor because I think it's a good signal to notify devs there are broken changes, we can use semver as a signal, but it probably not worth a major version upgrade, and as ad4m still not release as stable.
- I also expect more discussion and polish on the interface, it will helps when reaching community devs.

I actually reading your comments on previous PR with [subscription in PerspectiveProxy](https://github.com/perspect3vism/ad4m/pull/28#issuecomment-1017435156) and decide it probably better to make all the subscription request all in client class.

2022-07-26 19:07 UTC, lucksus commented
I agree with the notion of doing changes that improve the interface earlier, rather than later. But I don't regard these changes as improvements.

The discussion in the PR you linked is about how subscriptions are implemented, which can and so far is hidden from the interface Ad4mClient (and PerspectiveProxy) provides.

I think `PerspectiveProxy` should be the go-to interface for dealing with perspectives from the UI. In every context where we only need access to one perspective we should try to only pass down a PerspectiveProxy instead of the full Ad4mClient. Like for instance done in the `PerspectiveView` spec: https://github.com/perspect3vism/PIPs/blob/main/pip-0002.md
This PR would already break that spec since PerspectiveViews (and several views in Perspect3ve - don't know about Flux) only have a PerspectiveProxy AND need to register callbacks. I don't see a good reason for changing that.

Also, I don't think Ad4mClient users should be forced to understand (i.e. spent more time reading docs or code) how to activate callbacks. Default should be to have them turned on. I'm actually very fine with the state of this right now. I understand the whole reason for this effort is that you try to get rid of warnings in the console that show up when a user (=UI) doesn't have the cap tokens for some perspectives. I actually think the current stat is fine already, and these warnings are not a problem but providing good feedback for anybody who tries to understand more.

If you care about adding a feature where somebody who knows about capabilities and why that warning is there and doesn't want to be bothered, can then turn it of, please go ahead but don't break things :)

2022-07-27 20:46 UTC, lucksus approved these changes
👍

2022-07-28 14:40 UTC, jdeepee approved these changes

2022-07-28 14:57 UTC, merged